### ISSUE TITLE
Error: 'page_type'

### ISSUE THREAD

**Issue by lazarce** [Ayima/page-speed-blog-post#1]
Try #: 0
Error: 'page_type'
Error getting response. Sleeping for 1 hour.Try #0

**Comment by zazencodes** [comment]
If you would like help with this, please post the command you ran and the full error output @lazarce

**Comment by lazarce** [comment]
This is the command I used "python main.py --config-file config.json". I only followed the read me file.

**Comment by heather-ea** [comment]
I've just committed some changes that fix the bug. It should work now, but feel free to let me know if you come across any other issues.
